module.exports = {
    HEADER_CODE: 'X-WX-Code',
    LOGIN_TYPE: 'LOGIN-TYPE',
    HEADER_ENCRYPTED_DATA: 'X-WX-Encrypted-Data',
    HEADER_IV: 'X-WX-IV',
    HEADER_ID: 'X-WX-Id',
	
    HEADER_TOKEN: 'X-WX-Token',
	HEADER_TOKEN_KEY_NAME:'accessToken',
	
    SESSION_MAGIC_ID: 'F2C224D4-2BCE-4C64-AF9F-A6D872000D1A',

    ERR_INVALID_PARAMS: 'ERR_INVALID_PARAMS',

    ERR_LOGIN_FAILED: 'ERR_LOGIN_FAILED',
    ERR_GET_USER_INFO: 'ERR_GET_USER_INFO',
    ERR_LOGIN_TIMEOUT: 'ERR_LOGIN_TIMEOUT',
    ERR_LOGIN_FAILED: 'ERR_LOGIN_FAILED',
    ERR_LOGIN_SESSION_NOT_RECEIVED: 'ERR_LOGIN_MISSING_SESSION',

    ERR_INVALID_SESSION: 'ERR_INVALID_SESSION',
    ERR_CHECK_LOGIN_FAILED: 'ERR_CHECK_LOGIN_FAILED',
};